M48
; DRILL file {KiCad 9.0.6} date 2026-08-07T03:23:23+0300
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-07T03:23:23+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.250
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.500
%
G90
G05
T1
X78.5Y-41.5
X78.5Y-113.5
X200.5Y-41.5
X200.5Y-113.5
T2
X81.18Y-62.67
X81.18Y-75.37
T3
X78.07Y-52.5
M30
